import requests

#Getting the Code

#response_type=code                                 : The response type(default: code)
#client_id=1000.A3J98K1ZXAO1QHG3IP3QCEBKPP5LYM      : Client-ID, generated by the user
#scope=Desk.tickets.ALL                             : The scope of the request
#https://accounts.zoho.in/oauth/v2/auth?response_type=code&client_id=1000.H8U3OC2MZZNWYBTVI37HKTVHZQL2BH&scope=Desk.tickets.ALL&redirect_uri=http://127.0.0.1:5000/zoho/oauth/&state=randomstring123

def get_access_token(access_code):
    url = "https://accounts.zoho.in/oauth/v2/token"

    #Redirect URL can be an api or localhost for testing purposes
    #Client_id and client_secret are gotten from the user itself
    params = {
        "code": access_code,
        "grant_type": "authorization_code",
        "client_id": "1000.H8U3OC2MZZNWYBTVI37HKTVHZQL2BH",
        "client_secret": "c365e13ef588726e4af332c0faf7b82b9e1f298d48",
        "redirect_uri": "http://127.0.0.1:5000/zoho/oauth/"
    }

    response = requests.post(url, params=params)
    if response.status_code >= 200 and response.status_code <= 299:
        return response.json().get('access_token')


#From the Reponse, the Access code is retrieved.
#Access Token: 1000.87a1d88ba33d61c549c4411d441d6931.5f6832b52f7f483885683f0f64e68d3d


def get_ticket_data(access_token,org_id=None):
    url = "https://desk.zoho.in/api/v1/tickets"

    #Finally making the api call
    headers = {
        "Authorization": f"Zoho-oauthtoken {access_token}"
    }

    #Can Specify Organization ID if multiple are used
    if(org_id):
        headers["orgId"] = org_id

    response = requests.get(url, headers=headers)

    if response.status_code >= 200 and response.status_code <= 299:
        return response.json()